###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

$terminal = alacritty
$fileManager = dolphin
$menu = rofi -show drun

###################
### PERMISSIONS ###
###################

# See https://wiki.hypr.land/Configuring/Permissions/

################
### INCLUDES ###
################

source = ~/.config/hypr/conf/monitors.conf
source = ~/.config/hypr/conf/env.conf
source = ~/.config/hypr/conf/autostart.conf
source = ~/.config/hypr/conf/look-and-feel.conf
source = ~/.config/hypr/conf/input.conf
source = ~/.config/hypr/conf/keybinds.conf
source = ~/.config/hypr/conf/windowrules.conf
