#################
### AUTOSTART ###
#################

exec-once = waybar
exec-once = awww-daemon

# Idle daemon (auto-lock)
exec-once = hypridle

# Clipboard history (precisa rodar pra capturar)
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# Network e Bluetooth tray
exec-once = nm-applet --indicator
exec-once = blueman-applet
